export { default as View } from './View'
export { default as Container } from './Container'
export { default as Header } from './Header'
export { default as Body } from './Body'
export { default as Content } from './Content'
export { default as Aside } from './Aside'
export { default as Footer } from './Footer'
